### ISSUE TITLE
Cannot read property 'highest_tier_completed' of undefined

### ISSUE THREAD

**Issue by SaegusaMayumi1234** [Senither/hypixel-skyblock-facade#11]
this happened when I try to getting data for player: ImNotM0tor, UUID: "06049fd7c16140888bb1b29544bcfc50"

![image](https://user-images.githubusercontent.com/69360824/123751785-4c585d00-d8e2-11eb-9b3c-b1a6b6d4de56.png)

**Comment by Senither** [comment]
It should be fixed as of 42a95a1c37bc023b4b360605314db67791af77c4
Thanks for reporting the bug 👍
