### ISSUE TITLE
Enderman slayer feature request

### ISSUE THREAD

**Issue by SaegusaMayumi1234** [Senither/hypixel-skyblock-facade#7]
Feature request

I don't know if this already in progress but can you add voidgloom seraph/enderman slayer in API please? thank you so much.
![image](https://user-images.githubusercontent.com/69360824/120971891-5ed5ef80-c797-11eb-8780-54a6dadd2618.png)

**Comment by Senither** [comment]
I haven't started working on it yet, but I can work on adding it either later today(I'm currently at work, so would be in 10+ hours), or tomorrow, I'm still not sure what the enderman slayer would give in terms of weight so for now it would most likely just give 0 weight.

**Comment by SaegusaMayumi1234** [comment]
Alright thank you so much

**Comment by Senither** [comment]
There is support for it now, still not weight yet tho, that will come later 👍
